stages:
  vectorize_train_data:
    cmd: python src/vectorize_model_train_data.py data/model/WikiLarge_Train.csv data/reference/AoA_51715_words.csv data/reference/Concreteness_ratings_Brysbaert_et_al_BRM.txt data/reference/dale_chall.txt data/model/vectorized_train_lemma.pkl data/model/labels_lemma.pkl data/model/tfidf_lemma.pkl data/model/lemmatizer.pkl data/model/tokenized.pkl
    deps:
      - src/vectorize_model_train_data.py
      - data/model/WikiLarge_Train.csv
      - data/reference/AoA_51715_words.csv
      - data/reference/Concreteness_ratings_Brysbaert_et_al_BRM.txt
      - data/reference/dale_chall.txt
    outs:
      - data/model/vectorized_train_lemma.pkl
      - data/model/tfidf_lemma.pkl
      - data/model/labels_lemma.pkl
      - data/model/lemmatizer.pkl
      - data/model/tokenized.pkl
  generate_dummies:
    cmd: python src/dummies.py data/model/vectorized_train_lemma.pkl data/model/labels_lemma.pkl models/baseline/dummy_metrics.json
    deps:
      - src/basic_log_reg.py
      - data/model/vectorized_train_lemma.pkl
      - data/model/labels_lemma.pkl
    metrics:
      - models/baseline/dummy_metrics.json
  generate_baseline:
    cmd: python src/basic_log_reg.py data/model/vectorized_train_lemma.pkl data/model/labels_lemma.pkl models/baseline/baseline_model.pkl models/baseline/baseline_metrics.json
    deps:
      - src/basic_log_reg.py
      - data/model/vectorized_train_lemma.pkl
      - data/model/labels_lemma.pkl
    outs:
      - models/baseline/baseline_model.pkl
    metrics:
      - models/baseline/baseline_metrics.json
  generate_logreg_model:
    cmd: python src/model_log_reg.py data/model/vectorized_train_lemma.pkl data/model/labels_lemma.pkl models/supervised/logreg_model.pkl models/supervised/logreg_metrics.json
    deps:
      - src/model_log_reg.py
      - data/model/vectorized_train_lemma.pkl
      - data/model/labels_lemma.pkl
    outs:
      - models/supervised/logreg_model.pkl
    metrics:
      - models/supervised/logreg_metrics.json
#  generate_logreg_model_only_scores:
#    cmd: python src/model_log_reg_only_scores.py data/model/vectorized_train_lemma.pkl data/model/labels_lemma.pkl models/supervised/logreg_model_only_scores.pkl models/supervised/logreg_metrics_only_scores.json
#    deps:
#      - src/model_log_reg_only_scores.py
#      - data/model/vectorized_train_lemma.pkl
#      - data/model/labels_lemma.pkl
#    outs:
#      - models/supervised/logreg_model_only_scores.pkl
#    metrics:
#      - models/supervised/logreg_metrics_only_scores.json
  generate_rf_model_only_scores:
    cmd: python src/model_rf_only_scores.py data/model/vectorized_train_lemma.pkl data/model/labels_lemma.pkl models/supervised/rf_model_only_scores.pkl models/supervised/rf_metrics_only_scores.json
    deps:
      - src/model_rf_only_scores.py
      - data/model/vectorized_train_lemma.pkl
      - data/model/labels_lemma.pkl
    outs:
      - models/supervised/rf_model_only_scores.pkl
    metrics:
      - models/supervised/rf_metrics_only_scores.json
# [NOT NEEDED FOR NOW - TAKES SOME TIME]  vectorize_test_data:
#    cmd: python src/vectorize_model_test_data.py data/model/WikiLarge_Test.csv data/model/tfidf.pkl data/model/vectorized_test.pkl
#    deps:
#      - src/vectorize_model_test_data.py
#      - data/model/tfidf.pkl
#      - data/model/WikiLarge_Test.csv
#    outs:
#      - data/model/vectorized_test.pkl